from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP
from Crypto.Util import number

# RSA Encryption/Decryption
def rsa_encrypt(message, public_key):
    cipher = PKCS1_OAEP.new(public_key)
    ciphertext = cipher.encrypt(message)
    return ciphertext

def rsa_decrypt(ciphertext, private_key):
    cipher = PKCS1_OAEP.new(private_key)
    plaintext = cipher.decrypt(ciphertext)
    return plaintext

# Diffie-Hellman Key Exchange
def diffie_hellman():
    # Generate prime number and generator
    p = number.getPrime(128)
    g = 2
    # Choose private key
    private_key = number.getRandomRange(2, p - 2)
    # Compute public key
    public_key = pow(g, private_key, p)
    return p, g, private_key, public_key

# Example usage:
message = b'This is a secret message.'
rsa_key = RSA.generate(2048)

encrypted_message = rsa_encrypt(message, rsa_key.publickey())
decrypted_message = rsa_decrypt(encrypted_message, rsa_key)
print("Decrypted message:", decrypted_message.decode('utf-8'))

p, g, private_key, public_key = diffie_hellman()
print("Public key generated by Diffie-Hellman:", public_key)